Bootstrap: docker

From: continuumio/anaconda3

Stage: Paint-shop

%labels

PLACEHOLDER


%post

apt-get update \
    && apt-get install -y build-essential \
    && apt-get install -y wget \
    && apt-get install -y git bzip cmake libboost-all-dev parallel zlib1g-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

conda --version

conda install -n base -c conda-forge mamba

mkdir -p /app

cd /app

PROJECT_DIR=/app

mamba env create -n edta -c conda-forge -c bioconda edta

